import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import {
  Users,
  Search,
  Plus,
  Phone,
  GraduationCap,
  IndianRupee,
  Loader2,
} from 'lucide-react';
import CenterLayout from '@/layouts/CenterLayout';
import { useAuth } from '@/contexts/AuthContext';
import { useCenterStudents, useCreateStudent, type StudentWithDetails } from '@/hooks/useStudents';
import { useCourses } from '@/hooks/useCourses';
import { useCenterAuthorizations } from '@/hooks/useCenterCourses';
import { format } from 'date-fns';

export default function CenterStudents() {
  const { user } = useAuth();
  const centerId = user?.centerId;

  const { data: students = [], isLoading } = useCenterStudents(centerId);
  const { data: courses = [] } = useCourses();
  const { data: authorizations = [] } = useCenterAuthorizations(centerId);
  const createStudent = useCreateStudent();

  const [searchQuery, setSearchQuery] = useState('');
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
  const [activeTab, setActiveTab] = useState('course');
  const [newStudent, setNewStudent] = useState({
    name: '',
    date_of_birth: '',
    gender: '',
    phone: '',
    email: '',
    guardian_phone: '',
    address: '',
    city: '',
    state: '',
    pincode: '',
    course_id: '',
    fee_paid: '',
    fee_pending: '',
  });

  const filteredStudents = students.filter(
    (student) =>
      student.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      student.enrollment_no.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (student.course_name?.toLowerCase().includes(searchQuery.toLowerCase()) ?? false)
  );

  // Get authorized courses for this center
  const authorizedCourseIds = authorizations.map(a => a.course_id);
  const availableCourses = courses.filter(c => authorizedCourseIds.includes(c.id) && c.status === 'active');

  const handleAddStudent = async () => {
    if (!centerId || !newStudent.course_id) return;

    await createStudent.mutateAsync({
      center_id: centerId,
      course_id: newStudent.course_id,
      name: newStudent.name,
      phone: newStudent.phone,
      email: newStudent.email || null,
      date_of_birth: newStudent.date_of_birth || null,
      gender: newStudent.gender || null,
      guardian_phone: newStudent.guardian_phone || null,
      address: newStudent.address || null,
      city: newStudent.city || null,
      state: newStudent.state || null,
      pincode: newStudent.pincode || null,
      fee_paid: Number(newStudent.fee_paid) || 0,
      fee_pending: Number(newStudent.fee_pending) || 0,
      status: 'active',
      enrollment_no: '', // Will be generated by database trigger
    });

    setIsAddDialogOpen(false);
    setNewStudent({
      name: '',
      date_of_birth: '',
      gender: '',
      phone: '',
      email: '',
      guardian_phone: '',
      address: '',
      city: '',
      state: '',
      pincode: '',
      course_id: '',
      fee_paid: '',
      fee_pending: '',
    });
    setActiveTab('course');
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'active':
        return 'bg-success hover:bg-success/90';
      case 'completed':
        return 'bg-info hover:bg-info/90';
      case 'certified':
        return 'bg-warning hover:bg-warning/90';
      default:
        return '';
    }
  };

  const stats = {
    total: students.length,
    active: students.filter(s => s.status === 'active').length,
    completed: students.filter(s => s.status === 'completed').length,
    totalFees: students.reduce((sum, s) => sum + Number(s.fee_paid || 0), 0),
  };

  if (isLoading) {
    return (
      <CenterLayout>
        <div className="flex items-center justify-center min-h-[400px]">
          <Loader2 className="w-8 h-8 animate-spin text-primary" />
        </div>
      </CenterLayout>
    );
  }

  return (
    <CenterLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div>
            <h1 className="text-3xl font-heading font-bold text-foreground">Student Management</h1>
            <p className="text-muted-foreground mt-1">Manage admissions and student records</p>
          </div>
          <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
            <DialogTrigger asChild>
              <Button>
                <Plus className="w-4 h-4 mr-2" />
                New Admission
              </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[700px] max-h-[90vh] overflow-y-auto">
              <DialogHeader>
                <DialogTitle>New Student Admission</DialogTitle>
                <DialogDescription>
                  Complete the admission form for a new student.
                </DialogDescription>
              </DialogHeader>
              <Tabs value={activeTab} onValueChange={setActiveTab} className="mt-4">
                <TabsList className="grid w-full grid-cols-3">
                  <TabsTrigger value="course">Course</TabsTrigger>
                  <TabsTrigger value="personal">Personal</TabsTrigger>
                  <TabsTrigger value="fees">Fees</TabsTrigger>
                </TabsList>

                <TabsContent value="course" className="space-y-4 mt-4">
                  <div className="grid gap-4">
                    <div className="grid gap-2">
                      <Label>Select Course</Label>
                      <Select
                        value={newStudent.course_id}
                        onValueChange={(value) => setNewStudent({ ...newStudent, course_id: value })}
                      >
                        <SelectTrigger>
                          <SelectValue placeholder="Choose a course" />
                        </SelectTrigger>
                        <SelectContent>
                          {availableCourses.length === 0 ? (
                            <SelectItem value="none" disabled>No courses authorized for this center</SelectItem>
                          ) : (
                            availableCourses.map((course) => (
                              <SelectItem key={course.id} value={course.id}>
                                {course.name}
                              </SelectItem>
                            ))
                          )}
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                </TabsContent>

                <TabsContent value="personal" className="space-y-4 mt-4">
                  <div className="grid gap-4">
                    <div className="grid gap-2">
                      <Label>Full Name *</Label>
                      <Input
                        placeholder="Enter full name"
                        value={newStudent.name}
                        onChange={(e) => setNewStudent({ ...newStudent, name: e.target.value })}
                      />
                    </div>
                    <div className="grid grid-cols-3 gap-4">
                      <div className="grid gap-2">
                        <Label>Date of Birth</Label>
                        <Input
                          type="date"
                          value={newStudent.date_of_birth}
                          onChange={(e) => setNewStudent({ ...newStudent, date_of_birth: e.target.value })}
                        />
                      </div>
                      <div className="grid gap-2">
                        <Label>Gender</Label>
                        <Select
                          value={newStudent.gender}
                          onValueChange={(value) => setNewStudent({ ...newStudent, gender: value })}
                        >
                          <SelectTrigger>
                            <SelectValue placeholder="Select" />
                          </SelectTrigger>
                          <SelectContent>
                            <SelectItem value="male">Male</SelectItem>
                            <SelectItem value="female">Female</SelectItem>
                            <SelectItem value="other">Other</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                      <div className="grid gap-2">
                        <Label>Phone *</Label>
                        <Input
                          placeholder="+91 98765 43210"
                          value={newStudent.phone}
                          onChange={(e) => setNewStudent({ ...newStudent, phone: e.target.value })}
                        />
                      </div>
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="grid gap-2">
                        <Label>Email</Label>
                        <Input
                          type="email"
                          placeholder="student@email.com"
                          value={newStudent.email}
                          onChange={(e) => setNewStudent({ ...newStudent, email: e.target.value })}
                        />
                      </div>
                      <div className="grid gap-2">
                        <Label>Guardian Phone</Label>
                        <Input
                          placeholder="+91 98765 43210"
                          value={newStudent.guardian_phone}
                          onChange={(e) => setNewStudent({ ...newStudent, guardian_phone: e.target.value })}
                        />
                      </div>
                    </div>
                    <div className="grid gap-2">
                      <Label>Address</Label>
                      <Textarea
                        placeholder="Enter complete address"
                        value={newStudent.address}
                        onChange={(e) => setNewStudent({ ...newStudent, address: e.target.value })}
                      />
                    </div>
                    <div className="grid grid-cols-3 gap-4">
                      <div className="grid gap-2">
                        <Label>City</Label>
                        <Input
                          placeholder="City"
                          value={newStudent.city}
                          onChange={(e) => setNewStudent({ ...newStudent, city: e.target.value })}
                        />
                      </div>
                      <div className="grid gap-2">
                        <Label>State</Label>
                        <Input
                          placeholder="State"
                          value={newStudent.state}
                          onChange={(e) => setNewStudent({ ...newStudent, state: e.target.value })}
                        />
                      </div>
                      <div className="grid gap-2">
                        <Label>Pincode</Label>
                        <Input
                          placeholder="400001"
                          value={newStudent.pincode}
                          onChange={(e) => setNewStudent({ ...newStudent, pincode: e.target.value })}
                        />
                      </div>
                    </div>
                  </div>
                </TabsContent>

                <TabsContent value="fees" className="space-y-4 mt-4">
                  <div className="grid gap-4">
                    <div className="grid grid-cols-2 gap-4">
                      <div className="grid gap-2">
                        <Label>Fees Paid (₹)</Label>
                        <Input
                          type="number"
                          placeholder="0"
                          value={newStudent.fee_paid}
                          onChange={(e) => setNewStudent({ ...newStudent, fee_paid: e.target.value })}
                        />
                      </div>
                      <div className="grid gap-2">
                        <Label>Fees Pending (₹)</Label>
                        <Input
                          type="number"
                          placeholder="0"
                          value={newStudent.fee_pending}
                          onChange={(e) => setNewStudent({ ...newStudent, fee_pending: e.target.value })}
                        />
                      </div>
                    </div>
                  </div>
                </TabsContent>
              </Tabs>
              <DialogFooter className="mt-6">
                <Button variant="outline" onClick={() => setIsAddDialogOpen(false)}>
                  Cancel
                </Button>
                <Button
                  onClick={handleAddStudent}
                  disabled={createStudent.isPending || !newStudent.name || !newStudent.phone || !newStudent.course_id}
                >
                  {createStudent.isPending && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
                  Admit Student
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
          <Card className="border-0 shadow-card">
            <CardContent className="p-4">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                  <Users className="w-5 h-5 text-primary" />
                </div>
                <div>
                  <p className="text-2xl font-bold">{stats.total}</p>
                  <p className="text-sm text-muted-foreground">Total Students</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card className="border-0 shadow-card">
            <CardContent className="p-4">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-lg bg-success/10 flex items-center justify-center">
                  <GraduationCap className="w-5 h-5 text-success" />
                </div>
                <div>
                  <p className="text-2xl font-bold">{stats.active}</p>
                  <p className="text-sm text-muted-foreground">Active</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card className="border-0 shadow-card">
            <CardContent className="p-4">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-lg bg-info/10 flex items-center justify-center">
                  <GraduationCap className="w-5 h-5 text-info" />
                </div>
                <div>
                  <p className="text-2xl font-bold">{stats.completed}</p>
                  <p className="text-sm text-muted-foreground">Completed</p>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card className="border-0 shadow-card">
            <CardContent className="p-4">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-lg bg-warning/10 flex items-center justify-center">
                  <IndianRupee className="w-5 h-5 text-warning" />
                </div>
                <div>
                  <p className="text-2xl font-bold">₹{(stats.totalFees / 1000).toFixed(0)}K</p>
                  <p className="text-sm text-muted-foreground">Fees Collected</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Students Table */}
        <Card className="border-0 shadow-card">
          <CardHeader className="pb-4">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
              <CardTitle className="font-heading">All Students</CardTitle>
              <div className="relative w-full sm:w-72">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                <Input
                  placeholder="Search students..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-9"
                />
              </div>
            </div>
          </CardHeader>
          <CardContent>
            {filteredStudents.length === 0 ? (
              <div className="text-center py-12 text-muted-foreground">
                {students.length === 0 ? 'No students yet. Add your first admission!' : 'No students match your search.'}
              </div>
            ) : (
              <div className="rounded-lg border overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow className="bg-muted/50">
                      <TableHead>Student</TableHead>
                      <TableHead>Enrollment No</TableHead>
                      <TableHead>Course</TableHead>
                      <TableHead>Admission Date</TableHead>
                      <TableHead>Fees</TableHead>
                      <TableHead>Status</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredStudents.map((student) => (
                      <TableRow key={student.id} className="table-row-hover">
                        <TableCell>
                          <div>
                            <p className="font-medium">{student.name}</p>
                            <span className="text-sm text-muted-foreground flex items-center gap-1">
                              <Phone className="w-3 h-3" />
                              {student.phone}
                            </span>
                          </div>
                        </TableCell>
                        <TableCell>
                          <Badge variant="outline">{student.enrollment_no}</Badge>
                        </TableCell>
                        <TableCell>
                          <p className="font-medium">{student.course_name || 'N/A'}</p>
                        </TableCell>
                        <TableCell>
                          <span className="text-sm text-muted-foreground">
                            {format(new Date(student.admission_date), 'dd/MM/yyyy')}
                          </span>
                        </TableCell>
                        <TableCell>
                          <div className="text-sm">
                            <span className="text-success font-medium">₹{Number(student.fee_paid || 0).toLocaleString()}</span>
                            {Number(student.fee_pending || 0) > 0 && (
                              <span className="text-destructive ml-2">/ ₹{Number(student.fee_pending).toLocaleString()} pending</span>
                            )}
                          </div>
                        </TableCell>
                        <TableCell>
                          <Badge className={`capitalize ${getStatusColor(student.status || 'active')}`}>
                            {student.status || 'active'}
                          </Badge>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </CenterLayout>
  );
}
